In [20]:
import pandas as pd
import  numpy as np
from datetime import date

df = pd.DataFrame({'key1':list('aabba'),
                  'key2': ['one','two','one','two','one'],
                  'data1': ['1','3','5','7','9'],
                  'data2': ['2','4','6','8','10']})

In [2]:
df

data1 data2 key1 key2
0     1     2    a  one
1     3     4    a  two
2     5     6    b  one
3     7     8    b  two
4     9    10    a  one

In [6]:
df[df['key1']=='a']

data1 data2 key1 key2
0     1     2    a  one
1     3     4    a  two
4     9    10    a  one

In [17]:
df1 = df['key1'].unique()
type(df1)

numpy.ndarray

In [21]:
date(2018,8,17).weekday()X = np.ones(10)

4

In [22]:
X = np.ones(10)

In [23]:
X

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [46]:
from sklearn.model_selection import StratifiedKFold
X = np.ones(10)
y = [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
skf = StratifiedKFold(n_splits=4,shuffle=True)
for train, test in skf.split(X, y):
    print("%s %s" % (train, test),'---')

[0 2 3 4 6 7 9] [1 5 8] ---
[0 1 3 4 5 8 9] [2 6 7] ---
[1 2 3 4 5 6 7 8] [0 9] ---
[0 1 2 5 6 7 8 9] [3 4] ---


In [41]:
X = np.ones(10)
X[5]

1.0